[build]
  command = "flutter pub get && flutter build web --web-renderer html"
  publish = "build/web"
  
[build.environment]
  PYTHON_VERSION = "3.10"
  NODE_VERSION = "18"
  MISE_PYTHON_COMPILE = "false"
  FLUTTER_WEB_USE_SKIA = "false"

[context.production.environment]
  PYTHON_VERSION = "3.10"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200